services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_build_volume:/app/frontend/build
    command: [ "npm", "run", "build" ]

  backend:
    build:
      context: ./backend
    ports:
      - "80:80"
    volumes:
      - frontend_build_volume:/app/backend/static
    command:
      [
        "bash",
        "-c",
        "uvicorn app.server:app --host 0.0.0.0 --port 80 --reload"
      ]

volumes:
  frontend_build_volume: